#!/bin/sh

# Use neovim for vim if present.
command -v nvim >/dev/null && alias vim="nvim" vimdiff="nvim -d"

# Verbosity and settings that you pretty much just always are going to want.
alias \
	l="ls -agC" \
#	bat="cat /sys/class/power_supply/BAT?/capacity" \
	cp="cp -iv" \
	mv="mv -iv" \
	rm="rm -v" \
	mkd="mkdir -pv" \
	yt="youtube-dl --add-metadata -i" \
	yta="yt -x -f bestaudio/best" \
	ffmpeg="ffmpeg -hide_banner"

# Colorize commands when possible.
alias \
	ls="ls -hN --color=auto --group-directories-first" \
	grep="grep --color=auto" \
	diff="diff --color=auto" \
	ccat="highlight --out-format=ansi"

# These common commands are just too long! Abbreviate them.
alias \
	ka="killall" \
	g="git" \
	YT="youtube-viewer" \
	sdn="sudo shutdown -h now" \
	f="$FILE" \
	e="$EDITOR" \
	v="$EDITOR" \
	p="sudo apt" \

# This alias is important. It enables the `pauseallmpv` command.
alias mpv="mpv --input-ipc-server=/tmp/mpvsoc$(date +%s)"

# conda envs
alias \
    fastai="conda activate fastai" \
    de="conda deactivate" \
    tf="conda activate tf_12" \
    new="conda activate new_tf" \
    jb="jupyter notebook"

#dotfiles
alias dotfiles="/usr/bin/git --git-dir=$HOME/.dotfiles.git/ --work-tree=$HOME"

#nvim/init.vim
alias cfv="vim $HOME/.config/nvim/init.vim"
alias cfi="vim $HOME/.config/i3/config"
alias cfe="vim $HOME/.emacs.d/init.el"


# navigation
alias ..="cd .."
alias ...="cd ../.."
alias ....="cd ../../.."
alias .....="cd ../../../.."
alias ......="cd ../../../../.."

# EMACS alias
alias ee="swallow emacsclient --alternate-editor='' --create-frame"
alias sv="straw-viewer"


#dotfiles
alias config='/usr/bin/git --git-dir=/home/alkhaldieid/.cfg/ --work-tree=/home/alkhaldieid'
alias shared_config='/usr/bin/git --git-dir=/home/alkhaldieid/.shared_cfg/ --work-tree=/home/alkhaldieid'
